"""Score the M3 hand checks against their key files and write results/m3/resolution_report.md and
results/m3/handcheck_scores.json (docs/PLAN.md, M3, quality bar).

Merge sheet: a verdict starting with "ok" counts as correct. Bar: at least 48 of 50.
Duplicate sheet: "Same entity as: 1, 3" lists the candidates that are the same entity as the mention.
- before = share of mentions with at least one same-entity candidate (no resolution: all separate);
- after  = share of mentions where at least one same-entity candidate is still in a different cluster.
Bar: after at most half of before. Only the up-to-5 shown candidates are judged, so both rates are
lower bounds on the true duplicate rates.
"""

import json
import re
from collections import Counter

from graphrag.config import get_settings

MERGE_BAR = 48
LABEL_NOTE = ("First pass drafted by Claude (a different model from the gpt-oss-120b judge); reviewed and "
              "corrected by Rohith Kumar Reddipogula. Rule used: the same country across historical eras "
              "counts as one entity.")


def read_jsonl(path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]


def sheet_answers(text: str, field: str) -> list[str]:
    return [v.strip() for v in re.findall(rf"(?m)^- {re.escape(field)}: *(.*)$", text)]


def parse_same(answer: str, n_candidates: int, item: int) -> set[int]:
    head = answer.split("(")[0].strip().lower()
    if not head or head.startswith("none"):
        return set()
    nums = {int(x) for x in re.findall(r"\d+", head)}
    if not nums or max(nums) > n_candidates:
        raise ValueError(f"duplicate item {item}: answer {answer!r} does not fit {n_candidates} candidates")
    return nums


def main() -> None:
    s = get_settings()
    out = s.results_dir / "m3"
    cluster_of = {r["mention"]: r["cluster"] for r in read_jsonl(out / "clusters.jsonl")}

    # Merge precision.
    merge_key = json.loads((out / "merge_check_key.json").read_text())
    verdicts = sheet_answers((out / "merge_handcheck.md").read_text(encoding="utf-8"), "Verdict")
    assert len(verdicts) == len(merge_key) and all(verdicts), "every merge item needs a verdict"
    ok = [v.lower().startswith("ok") for v in verdicts]
    by_stratum = {}
    for k, good in zip(merge_key, ok):
        st = by_stratum.setdefault(k["stratum"], {"checked": 0, "correct": 0})
        st["checked"] += 1
        st["correct"] += good
    wrong = [{"item": i + 1, "stratum": k["stratum"], "a": k["a"], "b": k["b"], "verdict": v}
             for i, (k, v, good) in enumerate(zip(merge_key, verdicts, ok)) if not good]
    merge = {"checked": len(ok), "correct": sum(ok), "bar": MERGE_BAR, "pass": sum(ok) >= MERGE_BAR,
             "by_stratum": by_stratum, "wrong": wrong}

    # Duplicate rate before and after.
    dup_key = json.loads((out / "duplicate_check_key.json").read_text())
    answers = sheet_answers((out / "duplicate_handcheck.md").read_text(encoding="utf-8"), "Same entity as")
    assert len(answers) == len(dup_key) and all(answers), "every duplicate item needs an answer"
    before = after = 0
    items = []
    for i, (k, ans) in enumerate(zip(dup_key, answers), 1):
        same = parse_same(ans, len(k["candidates"]), i)
        same_ids = [k["candidates"][j - 1] for j in sorted(same)]
        apart = [c for c in same_ids if cluster_of[c] != cluster_of[k["mention"]]]
        before += bool(same_ids)
        after += bool(apart)
        items.append({"item": i, "mention": k["mention"], "same_candidates": len(same_ids),
                      "still_separate": len(apart), "flag": "FLAG" in ans})
    n = len(dup_key)
    dup = {"mentions": n, "before": before, "after": after,
           "rate_before": round(before / n, 4), "rate_after": round(after / n, 4),
           "bar": "after at most half of before", "pass": after <= before / 2,
           "same_entity_pairs": sum(x["same_candidates"] for x in items),
           "same_entity_pairs_still_separate": sum(x["still_separate"] for x in items),
           "flagged_era_items": sum(x["flag"] for x in items)}

    run = json.loads((out / "resolution_run.json").read_text())
    pilot = json.loads((out / "pilot.json").read_text())
    changes = json.loads((out / "bridge_link_changes.json").read_text())
    scores = {"labelling": LABEL_NOTE, "merge_precision": merge, "duplicate_rate": dup,
              "m3_passed": merge["pass"] and dup["pass"]}
    (out / "handcheck_scores.json").write_text(json.dumps(scores, indent=1, ensure_ascii=False) + "\n")

    br = run["bridge_link_recall"]["report"]
    t = pilot["thresholds"]
    lines = [
        "# M3 entity resolution report",
        "",
        "Generated by `scripts/m3_score_handchecks.py` from `results/m3/handcheck_scores.json`,",
        "`results/m3/resolution_run.json`, `results/m3/pilot.json` and `results/m3/bridge_link_changes.json`.",
        "All numbers are on the report split unless stated otherwise. Test questions were never used.",
        "",
        "## Result",
        "",
        f"M3 {'PASSED' if scores['m3_passed'] else 'FAILED'} the quality bar fixed in `docs/PLAN.md` (M3).",
        "",
        "| Criterion | Result | Bar | Pass |",
        "|---|---|---|---|",
        f"| Merge precision (hand check) | {merge['correct']} of {merge['checked']} correct | at least {MERGE_BAR} of 50 | {'yes' if merge['pass'] else 'no'} |",
        f"| Duplicate rate before -> after | {dup['before']} of {n} ({dup['rate_before']:.2f}) -> {dup['after']} of {n} ({dup['rate_after']:.2f}) | after at most half of before | {'yes' if dup['pass'] else 'no'} |",
        "| When unsure, do not merge | unsure verdicts and errors never merge; cannot-link and two-page rules applied | rule | yes |",
        "",
        "## Hand checks",
        "",
        f"- Labelling: {LABEL_NOTE}",
        "- Merge sheet: `results/m3/merge_handcheck.md`, 50 pairs sampled from inside the final clusters "
        "(indirect merges through union-find chains included). Key: `results/m3/merge_check_key.json`.",
        "",
        "| Kind of merge | Checked | Correct |",
        "|---|---|---|",
        *[f"| {k} | {v['checked']} | {v['correct']} |" for k, v in sorted(by_stratum.items())],
        "",
        *[f"- Wrong merge, item {w['item']} ({w['stratum']}): {w['verdict']}" for w in wrong],
        "",
        f"- Duplicate sheet: `results/m3/duplicate_handcheck.md`, {n} random mentions with up to 5 candidates each, "
        "chosen without the resolver. Key: `results/m3/duplicate_check_key.json`.",
        f"- Same-entity candidate pairs marked: {dup['same_entity_pairs']}; still in different clusters after M3: "
        f"{dup['same_entity_pairs_still_separate']}. Items flagged as a country across eras: {dup['flagged_era_items']}.",
        "- Only the shown candidates were judged, so both duplicate rates are lower bounds.",
        "",
        "## Thresholds and settings",
        "",
        f"- `t_low` = {t['t_low']} ({t['t_low_rule']}; {t['tune_bridge_links']} tune-split bridge links from dev gold triples).",
        "- `t_high`: off. Every candidate pair was judged by the LLM (dev gold has no same-name negatives).",
        f"- Fuzzy name ratio {t['fuzzy_min']}, name gate {t['name_gate']}, same-name partners per mention {t['exact_k']}.",
        f"- Judge: openai/gpt-oss-120b, prompt {run['judge_version']} (explicit roles), cannot-link and two-page rules, "
        "merges applied most confident first (E5 cosine, then pair ids).",
        "",
        "## Run",
        "",
        f"- Candidate pairs: {run['candidate_pairs']}; verdicts: {run['verdicts']}.",
        f"- Merges applied: {run['merges_applied']}; refused: {run['merges_rejected']}.",
        f"- Clusters: {run['clusters']['total']} ({run['clusters']['with_2_or_more_mentions']} with 2 or more mentions); "
        f"non-page mentions linked to a page: {run['non_page_mentions_linked_to_a_page']} of {run['non_page_mentions']}.",
        f"- LLM cost of the run (live calls): {run['llm']['cost_usd_live']} USD.",
        "",
        "## Bridge link recall (reported, not part of the bar)",
        "",
        "| | Links | Linked | Recall |",
        "|---|---|---|---|",
        f"| Before M3 (exact name matching) | {br['links']} | {br['before_exact_name']} | {br['recall_before']:.2f} |",
        f"| After M3 | {br['links']} | {br['after_m3']} | {br['recall_after']:.2f} |",
        "",
        f"M3 lost {changes['lost']} exact-name links and gained {changes['gained']} that exact matching cannot find "
        "(`results/m3/bridge_link_changes.json`). Decision for M4 (2026-10-09): keep the M3 clusters as they are and "
        "add exact-title links (mention name equals exactly one page title) as a separate, labelled edge type.",
        "",
    ]
    (out / "resolution_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"merge": {k: merge[k] for k in ("checked", "correct", "pass")},
                      "duplicates": {k: dup[k] for k in ("before", "after", "rate_before", "rate_after", "pass")},
                      "m3_passed": scores["m3_passed"]}, indent=1))


if __name__ == "__main__":
    main()
